drop table if exists programmer CASCADE;
create table programmer (id integer generated by default as identity, bugs_made integer not null, lpm integer not null, name varchar(255) not null, primary key (id));

